package model

var Models = []interface{}{
	&User{},
	&UserProfile{},
	&EmailVerification{},
	&ForumPost{},
	&ForumPostVersion{},
	&ForumComment{},
	&ForumFollow{},
	&ForumLike{},
	&CommentLike{},
	&ForumPoll{},
	&ForumPollOption{},
	&ForumPollVote{},
	&ForumSurvey{},
	&ForumSurveyBlock{},
	&ForumSurveyResponse{},
	&ForumSurveyAnswer{},
	&ForumReport{},
	&EvepartyInvestment{},
	&WechatArticle{},
	&WechatCookie{},
	&Notification{},
}
